---
version: "3.8"
services:
  mariadb:
    build: requirements/mariadb
    image: inception/mariadb:v1
    container_name: mariadb
    restart: on-failure
    cap_drop:
      - ALL
    env_file: .env
    healthcheck:
      test: mariadb-admin ping || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 2s
    networks:
      - inception
    volumes:
      - database-data:/var/lib/mysql

  nginx:
    build: requirements/nginx
    image: inception/nginx:v1
    container_name: nginx
    restart: on-failure
    depends_on:
      wordpress:
        condition: service_healthy
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - CHOWN
      - SETUID
      - SETGID
    env_file: .env
    healthcheck:
      test: curl -f -k https://localhost || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 2s
    networks:
      - inception
    ports:
      - 443:443
    volumes:
      - wordpress-data:/var/www/wordpress:ro

  wordpress:
    build: requirements/wordpress
    image: inception/wordpress:v1
    container_name: wordpress
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
    env_file: .env
    healthcheck:
      test: SCRIPT_NAME=/status SCRIPT_FILENAME=/status REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 2s
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/wordpress

networks:
  inception:

volumes:
  database-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ycornamu/data/database-data'
  wordpress-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ycornamu/data/wordpress-data'
